# Generated by Django 4.2.30 on 2026-06-07 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Stable identifier used by the frontend, e.g. 'top', 'inline', 'footer'.", max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('recommended_size', models.CharField(blank=True, help_text='e.g. 728×90 or 970×250', max_length=40)),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, help_text='Price for one booking period (USD).', max_digits=8)),
                ('duration_days', models.PositiveIntegerField(default=7, help_text='Length of one booking, in days (7 = weekly).')),
                ('capacity', models.PositiveIntegerField(default=1, help_text='How many adverts can run in this slot at once.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to stop selling this slot.')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser_name', models.CharField(max_length=120)),
                ('advertiser_email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(upload_to='ads/')),
                ('target_url', models.URLField(help_text='Where the banner links to.')),
                ('alt_text', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('live', 'Live'), ('rejected', 'Taken down / rejected'), ('expired', 'Expired')], default='pending_payment', max_length=20)),
                ('payment_reference', models.CharField(max_length=100, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='advertising.adslot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
