# Generated by Django 4.2.30 on 2026-06-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0003_capacity_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='adslot',
            name='dodo_product_id',
            field=models.CharField(blank=True, help_text="Dodo Payments product id for this slot's weekly booking, e.g. 'pdt_...'.", max_length=100),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='dodo_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='adslot',
            name='code',
            field=models.SlugField(help_text="Tool category id this slot targets, e.g. 'pdf', 'image', 'ai'.", max_length=40, unique=True),
        ),
    ]
