# Generated by Django 4.2.30 on 2026-06-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0004_adslot_dodo_product_id_advertisement_dodo_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='dodo_session_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
