# Generated by Django 4.2.30 on 2026-06-16 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertising', '0007_recommended_size_636x212'),
    ]

    operations = [
        migrations.AddField(
            model_name='adslot',
            name='dodo_monthly_product_id',
            field=models.CharField(blank=True, help_text="Dodo Payments product id for this slot's monthly booking. Falls back to DODO_ADVERT_MONTHLY_ID if blank.", max_length=100),
        ),
        migrations.AddField(
            model_name='adslot',
            name='price_monthly_usd',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Monthly (30-day) price for one booking period (USD).', max_digits=8),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='billing_period',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adslot',
            name='duration_days',
            field=models.PositiveIntegerField(default=7, help_text='Length of one weekly booking, in days (7 = weekly).'),
        ),
        migrations.AlterField(
            model_name='adslot',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weekly price for one booking period (USD).', max_digits=8),
        ),
    ]
