# Generated by Django 4.2.30 on 2026-06-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0009_advert_prices_10_30'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adslot',
            name='price_monthly_usd',
            field=models.DecimalField(decimal_places=2, default=30, help_text='Monthly (30-day) price for one booking period (USD).', max_digits=8),
        ),
        migrations.AlterField(
            model_name='adslot',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Weekly price for one booking period (USD).', max_digits=8),
        ),
    ]
