# Generated by Django 4.2.30 on 2026-06-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0010_alter_adslot_price_monthly_usd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adslot',
            name='dodo_monthly_product_id',
        ),
        migrations.RemoveField(
            model_name='adslot',
            name='dodo_product_id',
        ),
    ]
